import { ChevronRight } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";

export function AccountSettingsPage({ onLogout }: { onLogout: () => void }) {
  const nav = useNavigate(); const sessionQuery = useQuery({ queryKey: ["account-session"], queryFn: api.getSession, retry: false }); const actor = sessionQuery.data?.actor; const home = sessionQuery.data?.home;
  return <div className="account-page"><section className="account-intro"><span className="eyebrow">ACCOUNT SETTINGS</span><h2>Keep your access clear.</h2><p>Review the home this browser can access, manage privacy choices, or sign out when you are finished.</p></section><div className="account-grid"><section className="panel account-card"><span className="eyebrow">SIGNED IN AS</span><h3>{actor?.name ?? "Current caregiver"}</h3><dl className="account-details"><div><dt>Role</dt><dd>{actor?.role ?? "—"}</dd></div><div><dt>Home</dt><dd>{home?.name ?? "ONE home"}</dd></div><div><dt>Home ID</dt><dd><code>{home?.id ?? sessionStorage.getItem("one_home_id") ?? "—"}</code></dd></div><div><dt>Session</dt><dd>Browser-only bearer session</dd></div></dl></section><section className="panel account-card"><span className="eyebrow">PRIVACY</span><h3>Your choices stay visible.</h3><p className="muted">Pause care, withdraw purpose-specific consent, or request your home data from the privacy center.</p><button type="button" className="secondary-button" onClick={() => nav("/dashboard/privacy")}>Open Privacy & consent <ChevronRight size={16} /></button></section></div><section className="panel account-signout"><div><span className="eyebrow">FINISHED FOR NOW?</span><h3>Sign out of this browser.</h3><p className="muted">ONE revokes the current server session and clears this browser’s local credentials.</p></div><button type="button" className="secondary-button danger-outline" onClick={onLogout}>Sign out <ChevronRight size={16} /></button></section></div>;
}
