import { useEffect, useState } from "react";
import { ChevronRight, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { api, clearSession } from "../api/client";

export function LoginPage() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [challenge, setChallenge] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setError(""); try { if (!challenge) { const result = await api.requestEmailCode("login", email); setChallenge(true); if (result.dev_code) setCode(result.dev_code); } else { await api.verifyEmailCode(email, code); navigate("/dashboard", { replace: true }); } } catch { clearSession(); setError(challenge ? "That email code is invalid or expired. Request a new one." : "We could not find an account for that email."); } finally { setBusy(false); } };
  return <div className="join-page"><form className="join-card panel" onSubmit={submit}><div className="join-brand" aria-label="ONE"><img className="one-logo large" src="/one-logo.png" alt="" aria-hidden="true" /><span className="eyebrow">WELCOME TO ONE</span></div><h1>Stay close to what matters.</h1><p className="muted">Use the email attached to your ONE care space. We’ll send a six-digit sign-in code so your home or residence stays with you when you change phones.</p><label htmlFor="login-email">Email address<input id="login-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" autoFocus={!challenge} /></label>{challenge && <label htmlFor="login-code">Email code<input id="login-code" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="123456" inputMode="numeric" autoComplete="one-time-code" autoFocus /></label>}{error && <div className="error-note" role="alert">{error}</div>}<button className="primary-button full-width" type="submit" disabled={busy || !email || (challenge && code.length !== 6)}>{busy ? "Checking securely…" : challenge ? "Open my care space" : "Email me a code"} <ChevronRight size={16} /></button><div className="join-divider"><span>NEW TO ONE?</span></div><button type="button" className="secondary-button full-width" onClick={() => navigate("/create-account")}>Create your ONE care space <ChevronRight size={16} /></button><button type="button" className="text-button login-invite-link" onClick={() => navigate("/join-household")}>Join an existing care space</button><p className="muted login-footnote">Your session stays in this browser until you sign out.</p></form></div>;
}

export function AccountPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", home: "", careSetting: "home" as "home" | "residence", supportFocus: "mci" as "general" | "mci" }); const [challenge, setChallenge] = useState<{ email: string; code: string; devCode?: string | null } | null>(null); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { if (!challenge) { const created = await api.requestEmailCode("create", form.email, form.name, form.home, form.careSetting, form.supportFocus); setChallenge({ email: form.email, code: created.verification_id, devCode: created.dev_code }); if (created.dev_code) setCode(created.dev_code); } else { await api.verifyEmailCode(challenge.email, code); navigate("/onboarding", { replace: true }); } } catch { setError("We could not create this care space. Check the details and try again."); } finally { setBusy(false); } };
  return <div className="join-page"><form className="join-card panel" onSubmit={submit}><img className="one-logo large" src="/one-logo.png" alt="" aria-hidden="true" /><span className="eyebrow">CREATE YOUR ONE CARE SPACE</span><h1>Care, together.</h1><p className="muted">Set up ONE for a private home or a residential care setting. ONE is designed to support daily routines and human follow-up for people living with mild cognitive impairment (MCI), without diagnosing or replacing clinical care.</p><label>Your name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} autoComplete="name" /></label><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} autoComplete="email" disabled={Boolean(challenge)} /></label><label>Home or residence name<input value={form.home} onChange={(event) => setForm({ ...form, home: event.target.value })} placeholder={form.careSetting === "residence" ? "Residence name" : "ONE Home"} /></label><label>Care setting<select value={form.careSetting} onChange={(event) => setForm({ ...form, careSetting: event.target.value as "home" | "residence" })} disabled={Boolean(challenge)}><option value="home">Private home / household</option><option value="residence">Residential care / assisted living</option></select></label><label>Support focus<select value={form.supportFocus} onChange={(event) => setForm({ ...form, supportFocus: event.target.value as "general" | "mci" })} disabled={Boolean(challenge)}><option value="mci">Mild cognitive impairment (MCI) support</option><option value="general">General cognitive and daily-routine support</option></select></label>{error && <div className="error-note" role="alert">{error}</div>}{challenge && <div className="pairing-code" role="status"><span className="eyebrow">CHECK YOUR EMAIL</span><strong>{challenge.devCode ? `Local code ${challenge.devCode}` : "A six-digit code was sent"}</strong><span className="muted">This code expires in 10 minutes and can be used once.</span></div>}{challenge && <label htmlFor="account-email-code">Email code<input id="account-email-code" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" placeholder="123456" /></label>}<button className="primary-button full-width" disabled={busy || (challenge ? code.length !== 6 : false)}>{busy ? "Working securely…" : challenge ? "Verify and continue" : "Email me a code"} <ChevronRight size={16} /></button><button type="button" className="text-button" onClick={() => navigate("/login")}>Already have an account? Sign in</button></form></div>;
}

const onboardingKey = () => `one_onboarding_complete:${sessionStorage.getItem("one_home_id") ?? "unknown"}:${sessionStorage.getItem("one_user_id") ?? "unknown"}`;

export function OnboardingPage({ onComplete }: { onComplete: () => void }) {
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [granted, setGranted] = useState<boolean | null>(null); const [error, setError] = useState("");
  const steps = [{ purpose: "video_capture", title: "A clear view, with consent", copy: "Use camera observations to support daily routines in a home or residence, including MCI support built around the person’s own baseline." }, { purpose: "audio_capture", title: "Natural conversations", copy: "Use the microphone so daily check-ins can feel easy and human for residents and people at home." }, { purpose: "family_mode", title: "Share care, intentionally", copy: "Let trusted family, caregivers, or residence staff see only the context they need, with clear roles." }, { purpose: "medication_management", title: "Keep reminders together", copy: "Organize human-entered reminders and acknowledgements for the care team without giving medical advice." }];
  const current = steps[step]; useEffect(() => { setGranted(null); setError(""); }, [step]);
  const next = async () => { if (granted === null) return; setBusy(true); setError(""); try { await api.giveConsent(current.purpose, granted); if (step === steps.length - 1) { localStorage.setItem(onboardingKey(), "true"); onComplete(); } else setStep(step + 1); } catch { setError("We could not save this choice. Check the local connection and try again."); } finally { setBusy(false); } };
  return <div className="join-page"><section className="join-card panel"><div className="join-brand" aria-label="ONE"><img className="one-logo large" src="/one-logo.png" alt="" aria-hidden="true" /><span className="eyebrow">SET UP ONE</span></div><div className="onboarding-progress" role="progressbar" aria-label={`Onboarding step ${step + 1} of ${steps.length}`} aria-valuemin={1} aria-valuemax={steps.length} aria-valuenow={step + 1}><span style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div><div className="onboarding-step-meta"><span>STEP {step + 1} OF {steps.length}</span><span>{current.purpose.replaceAll("_", " ")}</span></div><h1>{current.title}</h1><p className="muted">{current.copy} You can change this choice any time in Privacy & consent.</p><fieldset className="consent-choice"><legend>Choose for this home</legend><p className="consent-guidance">This choice only controls this purpose. Nothing starts until you choose.</p><div className="consent-choice-options" aria-label="Consent choice"><label className={`consent-option ${granted === true ? "selected" : ""}`}><input type="radio" name="onboarding-consent" checked={granted === true} onChange={() => setGranted(true)} /><span className="consent-option-copy"><strong>Allow</strong><span>Enable this purpose for your care circle.</span></span><span className="consent-option-mark" aria-hidden="true">{granted === true ? "✓" : ""}</span></label><label className={`consent-option ${granted === false ? "selected" : ""}`}><input type="radio" name="onboarding-consent" checked={granted === false} onChange={() => setGranted(false)} /><span className="consent-option-copy"><strong>Not now</strong><span>Keep this data source off for now.</span></span><span className="consent-option-mark" aria-hidden="true">{granted === false ? "✓" : ""}</span></label></div></fieldset>{error && <div className="error-note" role="alert">{error}</div>}<div className="onboarding-actions">{step > 0 && <button type="button" className="secondary-button" onClick={() => setStep((value) => value - 1)}>Back</button>}<button type="button" className="primary-button" onClick={() => void next()} disabled={busy || granted === null}>{busy ? "Saving your choice…" : step === steps.length - 1 ? "Finish setup" : "Continue"} <ChevronRight size={16} /></button></div><div className="onboarding-privacy-note"><ShieldCheck size={16} /><span><strong>You stay in control.</strong> Change or withdraw this choice later in Privacy & consent.</span></div><p className="muted onboarding-note">Complete each purpose choice to finish setup. Choosing “Not now” keeps that data source off.</p></section></div>;
}

export { onboardingKey };
