import { lazy, Suspense, useState } from "react";
import { Camera, Video } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { api, demoMode } from "../api/client";
import type { LastSeenObject, Scene } from "../models/domain";
import { formatTime } from "./shared";

const RoomScene3D = lazy(() => import("../map/RoomScene3D").then((module) => ({ default: module.RoomScene3D })));

export function MapPage({ objects, scene }: { objects: LastSeenObject[]; scene: Scene }) {
  const [selected, setSelected] = useState(objects[0]?.id);
  const [view, setView] = useState<"3d" | "2d">("3d");
  const mapQuery = useQuery({ queryKey: ["current-map"], queryFn: api.getCurrentMap, enabled: demoMode || Boolean(sessionStorage.getItem("one_access_token")), retry: false });
  const cameraQuery = useQuery({ queryKey: ["camera"], queryFn: api.getDevice, enabled: demoMode || Boolean(sessionStorage.getItem("one_access_token")), retry: false });
  const current = objects.find((object) => object.id === selected);
  return <div className="map-layout"><section className="map-panel panel"><div className="panel-heading"><div><span className="eyebrow">ROOMPLAN-DERIVED VIEW · REVISION {mapQuery.data?.revision ?? scene.version}</span><h2>Familiar places, gently remembered.</h2></div><div className="view-toggle"><button className={view === "3d" ? "active" : ""} onClick={() => setView("3d")}>3D</button><button className={view === "2d" ? "active" : ""} onClick={() => setView("2d")}>2D</button></div></div><div className="scene-wrap">
    {view === "3d" ? <Suspense fallback={<div className="three-scene loading-scene">Loading room view…</div>}><RoomScene3D scene={scene} objects={objects} selectedId={selected} onSelect={setSelected} /></Suspense> : <div className="scene-grid" aria-label="2D accessible floor plan fallback"><div className="scene-label living-label">LIVING ROOM</div><div className="scene-label entry-label">ENTRYWAY</div><div className="scene-label kitchen-label">KITCHEN</div><div className="scene-label bedroom-label">BEDROOM</div>{objects.filter((object) => object.point).map((object) => <button key={object.id} className={`map-marker ${selected === object.id ? "selected" : ""}`} style={{ left: `${object.point!.x}%`, top: `${object.point!.y}%` }} onClick={() => setSelected(object.id)} aria-label={`${object.label}, ${object.zone?.name ?? "location unknown"}`}><span>{object.icon}</span></button>)}<span className="camera-frustum" aria-hidden="true"><Camera size={13} /> camera</span></div>}
    <div className="scene-legend"><span><i className="legend-dot precise" /> Estimated point</span><span><i className="legend-dot zone" /> Zone fallback</span><span>{view === "3d" ? "Drag-free overview · select a marker" : "Scale · 1 square = 1m"}</span></div><div className="map-data-note" role="status"><strong>Map data</strong> · revision {mapQuery.data?.revision ?? scene.version} · {mapQuery.data?.coordinate_frame ?? scene.coordinateFrame ?? "coordinate frame not reported"}.{!scene.sceneId || scene.sceneId === "scene-empty" ? " No RoomPlan map is available." : ""}</div>
  </div></section><aside className="map-side"><div className="panel selected-object"><span className="eyebrow">SELECTED MEMORY</span>{current ? <><div className="selected-title"><span className="object-symbol">{current.icon}</span><div><h2>{current.label}</h2><span className="muted">Last seen {formatTime(current.lastSeenAt)}</span></div></div><div className="confidence-meter"><div><span>Confidence</span><strong>{Math.round(current.confidence * 100)}%</strong></div><div className="meter"><span style={{ width: `${current.confidence * 100}%` }} /></div><p>{current.point ? `Estimated within ${current.confidenceRadiusM}m of this point.` : `Point is uncertain; showing the ${current.zone?.name ?? "nearest"} zone instead.`}</p></div><button className="secondary-button full-width"><Video size={16} /> View source clip</button></> : <p className="muted">Select an object on the map.</p>}</div><div className="panel calibration-card"><span className="eyebrow">FIXED CAMERA</span><h3>{cameraQuery.data ? "Camera connection" : "No camera connected"}</h3><p className="muted">{cameraQuery.data ? `${cameraQuery.data.label} · ${cameraQuery.data.status}` : "Connect a fixed camera to record calibration."}</p><p className="calibration-state" role="status"><strong>Calibration state:</strong> not reported by the current API.</p><p className="muted small-copy">Automatic projection is unavailable here. Markers without a reliable point fall back to their zone; ONE does not claim automatic localization.</p></div></aside></div>;
}
