import { lazy, Suspense, useState } from "react";
import { Camera, Video } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { api, demoMode, normalizeZones } from "../api/client";
import type { LastSeenObject, Scene } from "../models/domain";
import { formatTime } from "./shared";

const RoomScene3D = lazy(() => import("../map/RoomScene3D").then((module) => ({ default: module.RoomScene3D })));

export function MapPage({ objects, scene }: { objects: LastSeenObject[]; scene: Scene }) {
  const normalizedScene = { ...scene, zones: normalizeZones(scene.zones) };
  const [selected, setSelected] = useState(objects[0]?.id);
  const [view, setView] = useState<"3d" | "2d">("3d");
  const hasSession = demoMode || Boolean(sessionStorage.getItem("one_access_token"));
  const mapQuery = useQuery({ queryKey: ["current-map"], queryFn: api.getCurrentMap, enabled: hasSession, retry: false });
  const cameraQuery = useQuery({ queryKey: ["camera"], queryFn: api.getDevice, enabled: hasSession, retry: false });
  const calibrationQuery = useQuery({ queryKey: ["calibrations"], queryFn: api.getCalibrations, enabled: hasSession, retry: false });
  const current = objects.find((object) => object.id === selected);
  const activeCalibration = calibrationQuery.data?.find((calibration) => calibration.status === "active" && calibration.camera_id === cameraQuery.data?.id);
  return <div className="map-layout"><section className="map-panel panel"><div className="panel-heading"><div><span className="eyebrow">ROOMPLAN-DERIVED VIEW · REVISION {mapQuery.data?.revision ?? normalizedScene.version}</span><h2>Familiar places, gently remembered.</h2></div><div className="view-toggle"><button className={view === "3d" ? "active" : ""} onClick={() => setView("3d")}>3D</button><button className={view === "2d" ? "active" : ""} onClick={() => setView("2d")}>2D</button></div></div><div className="scene-wrap">
    {view === "3d" ? <Suspense fallback={<div className="three-scene loading-scene">Loading room view…</div>}><RoomScene3D scene={normalizedScene} objects={objects} selectedId={selected} onSelect={setSelected} /></Suspense> : <div className="scene-grid" aria-label="2D accessible floor plan fallback">{normalizedScene.zones.map((zone) => <span key={zone.id} className="scene-label scene-zone-label" style={{ left: `${zone.x + zone.width / 2}%`, top: `${zone.y + zone.height / 2}%` }}>{zone.name.toUpperCase()}</span>)}{!normalizedScene.zones.length && <div className="scene-empty-state"><strong>No room zone yet</strong><span>Complete camera calibration to add the first familiar place.</span></div>}{objects.filter((object) => object.point).map((object) => <button key={object.id} className={`map-marker ${selected === object.id ? "selected" : ""}`} style={{ left: `${object.point!.x}%`, top: `${object.point!.y}%` }} onClick={() => setSelected(object.id)} aria-label={`${object.label}, ${object.zone?.name ?? "location unknown"}`}><span>{object.icon}</span></button>)}<span className="camera-frustum" aria-hidden="true"><Camera size={13} /> camera</span></div>}
    <div className="scene-legend"><span><i className="legend-dot precise" /> Estimated point</span><span><i className="legend-dot zone" /> Zone fallback</span><span>{view === "3d" ? "Drag-free overview · select a marker" : "Scale · 1 square = 1m"}</span></div><div className="map-data-note" role="status"><strong>Map data</strong> · revision {mapQuery.data?.revision ?? normalizedScene.version} · {mapQuery.data?.coordinate_frame ?? normalizedScene.coordinateFrame ?? "coordinate frame not reported"}.{!normalizedScene.sceneId || normalizedScene.sceneId === "scene-empty" ? " No RoomPlan map is available." : ""}</div>
</div></section><aside className="map-side"><div className="panel selected-object"><span className="eyebrow">SELECTED MEMORY</span>{current ? <><div className="selected-title"><span className="object-symbol">{current.icon}</span><div><h2>{current.label}</h2><span className="muted">Last seen {formatTime(current.lastSeenAt)}</span></div></div><div className="confidence-meter"><div><span>Confidence</span><strong>{Math.round(current.confidence * 100)}%</strong></div><div className="meter"><span style={{ width: `${current.confidence * 100}%` }} /></div><p>{current.point ? `Estimated within ${current.confidenceRadiusM}m of this point.` : `Point is uncertain; showing the ${current.zone?.name ?? "nearest"} zone instead.`}</p></div><button className="secondary-button full-width"><Video size={16} /> View source clip</button></> : <p className="muted">{normalizedScene.zones.length ? "Select an object on the map." : "Your calibrated room will appear here once it has a saved zone."}</p>}</div><div className="panel calibration-card"><span className="eyebrow">FIXED CAMERA</span><h3>{cameraQuery.data ? "Camera connection" : "No camera connected"}</h3><p className="muted">{cameraQuery.data ? `${cameraQuery.data.label} · ${cameraQuery.data.status}` : "Connect a fixed camera to record calibration."}</p><p className="calibration-state" role="status"><strong>Calibration state:</strong> {activeCalibration ? `Active · estimated error ${activeCalibration.accuracy_m ?? "not reported"}m` : "Not calibrated yet."}</p><p className="muted small-copy">{activeCalibration ? "Three caregiver-confirmed anchors keep locations approximate and reviewable." : "Complete camera setup from the pairing sheet to add reliable room anchors."}</p></div></aside></div>;
}
