import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Brain, Heart, Home, Mail, ShieldCheck, Sun, Users } from "lucide-react";
import "./registerPresentation.css";

export function RegisterPresentation() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [homeName, setHomeName] = useState("");
  const [setting, setSetting] = useState("Private home");
  const [support, setSupport] = useState("Memory and wellbeing");
  const [familyUpdates, setFamilyUpdates] = useState(true);
  const [careTeam, setCareTeam] = useState(false);
  const [plan, setPlan] = useState("Home");
  const [yearly, setYearly] = useState(false);
  useEffect(() => { window.scrollTo(0, 0); }, [step]);
  const active = [0, 1, 1, 2, 2][step];
  const price = plan === "Home" ? yearly ? "€279" : "€29" : yearly ? "€853" : "€79";
  const period = yearly ? "/year" : "/month";
  const next = () => step === 4 ? navigate("/dashboard") : setStep(step + 1);
  return <main className="one-figma-register"><div className="one-figma-register-art" aria-hidden="true"/><div className="one-figma-register-side"><section className={`one-figma-register-card ${step===0?"first":""}`}><Link to="/" className="one-figma-register-logo" aria-label="ONE home"><img src="/one-logo.png" alt=""/><strong>one</strong></Link>{step>0&&<div className="one-figma-register-steps">{["Your space","Support","Review"].map((label,index)=><span key={label} className={index===active?"active":index<active?"done":""}><b>{index<active?"✓":index+1}</b><small>{label}</small></span>)}</div>}
    {step===0&&<><h1>Create your care space</h1><p>Set up a private home or residential care setting, then choose the support and consent options you want to enable.</p><div className="one-figma-form"><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Alex Taylor"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="e.g. name@youremail.com"/></label><label>Home or residence name<input value={homeName} onChange={e=>setHomeName(e.target.value)} placeholder="e.g. Oak View House"/></label><label>Care setting<select value={setting} onChange={e=>setSetting(e.target.value)}><option>Private home</option><option>Residence</option></select></label><label>Support focus<select value={support} onChange={e=>setSupport(e.target.value)}><option>Memory and wellbeing</option><option>Daily routines</option><option>Safety and reassurance</option><option>Social connection</option></select></label></div><button className="one-figma-primary" onClick={next}>Continue to support</button><p className="one-figma-signin">Already have an account? <Link to="/login">Sign in</Link></p></>}
    {step===1&&<><h1>Choose your support</h1><p>Tell us what would make care feel more personal, useful and comfortable.</p><div className="one-figma-support"><h2>Support focus</h2><div className="one-figma-support-grid">{[["Daily routines",Sun],["Memory and wellbeing",Brain],["Safety and reassurance",ShieldCheck],["Social connection",Users]].map(([label,Icon])=><button key={String(label)} className={support===label?"selected":""} onClick={()=>setSupport(String(label))}><Icon size={21}/><span>{String(label)}</span><b>{support===label?"✓":""}</b></button>)}</div><h2>Preferences</h2><button className={familyUpdates?"selected":""} onClick={()=>setFamilyUpdates(!familyUpdates)}><Users size={21}/><span>Keep family members updated</span><b>{familyUpdates?"✓":""}</b></button><button className={careTeam?"selected":""} onClick={()=>setCareTeam(!careTeam)}><Heart size={21}/><span>Coordinate support with the care team</span><b>{careTeam?"✓":""}</b></button></div><div className="one-figma-register-actions"><button onClick={()=>setStep(0)}>Back</button><button onClick={next}>Continue <ArrowRight size={16}/></button></div></>}
    {step===2&&<><h1>Choose your care plan</h1><p>Select the plan that fits your care space.</p><div className="one-figma-billing"><button className={!yearly?"active":""} onClick={()=>setYearly(false)}>Monthly</button><button className={yearly?"active":""} onClick={()=>setYearly(true)}>Yearly</button><span>Save 20%</span></div><div className="one-figma-plan-list">{[["Home","For private homes",yearly?"€279":"€29"],["Residence","For residence care settings",yearly?"€853":"€79"]].map(([label,description,cost])=><button key={label} className={plan===label?"selected":""} onClick={()=>setPlan(label)}><b className="one-figma-radio"/><span><strong>{label}</strong><small>{description}</small><em>● Personal care space<br/>● Support preferences<br/>● Family updates</em></span><strong>{cost}<small>{period}</small></strong></button>)}</div><div className="one-figma-register-actions"><button onClick={()=>setStep(1)}>Back</button><button onClick={next}>Continue to review <ArrowRight size={16}/></button></div></>}
    {step===3&&<><h1>Review your care space</h1><p>Everything looks ready. Check your details before opening the presentation.</p><div className="one-figma-review"><section><strong>Your details</strong><p><Users size={18}/>{name||"Alex Taylor"}</p><p><Mail size={18}/>{email||"alex@example.com"}</p><p><Home size={18}/>{homeName||"Oak View House"}</p></section><section><strong>Care setting</strong><p><Home size={18}/>{setting}</p><strong>Support focus</strong><p><Heart size={18}/>{support}</p></section></div><label className="one-figma-consent"><input type="checkbox" defaultChecked/> I agree to the <a href="/legal/privacy-notice.html#terms">Terms</a> and <a href="/legal/privacy-notice.html#privacy">Privacy Notice</a>.</label><div className="one-figma-register-actions"><button onClick={()=>setStep(2)}>Back to edit</button><button onClick={next}>Continue <ArrowRight size={16}/></button></div></>}
    {step===4&&<><h1>Secure Payment</h1><p>Review the selected plan. This presentation does not request or process a payment.</p><div className="one-figma-payment"><strong>Order summary</strong><div><b>{plan}</b><b>{price}<small>{period}</small></b></div><small>For {setting.toLowerCase()} care settings</small><hr/><p>Billing cycle <strong>{yearly?"Yearly":"Monthly"}</strong></p><p>Included features <span>Personal care space · Support preferences · Family updates</span></p></div><h2 className="one-figma-payment-title">Payment method</h2><div className="one-figma-payment-tabs"><span>Pay with card</span><span>Pay with bank transfer</span></div><div className="one-figma-payment-fields"><label>Card number<input disabled placeholder="1234 5678 9001"/></label><label>Expiry date<input disabled placeholder="01/23"/></label><label>CVC<input disabled placeholder="123"/></label><label>Name on the card<input disabled placeholder="Your Name"/></label><label>Billing email<input disabled placeholder="Email"/></label><label>Country<select disabled><option>Ireland</option></select></label></div><div className="one-figma-payment-total"><strong>Total</strong><strong>{price}<small>{period}</small></strong></div><button className="one-figma-primary" onClick={next}>Open demo dashboard <ArrowRight size={16}/></button><button className="one-figma-payment-back" onClick={()=>setStep(3)}>Back to review</button></>}
    <div className="one-figma-presentation-note">Presentation mode · no account or payment required</div></section></div></main>;
}
